version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INIT_DB_ROOT_USERNAME: ${MONGO_INIT_DB_ROOT_USERNAME}
      MONGO_INIT_DB_ROOT_PASSWORD: ${MONGO_INIT_DB_ROOT_PASSWORD}
      MONGO_INIT_DATABASE: ${MONGO_INIT_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'
  web: 
    build: .
    command: sh -c "uvicorn main:app --reload --host=0.0.0.0 --port=8000"
    ports:
      - 8000:8000